<div class="row">
    <div class="col-xs-2"></div>
    <div class="col-xs-8">
        <div class="alert messageBox" role="alert">
            <div class="message"></div>
        </div>
        <form id="mailForm">
            <div class="form-group">
                <label for="mailAddress">Email address:</label>
                <input type="email" class="form-control mailAddress" name="mailAddress" placeholder="email@domain.net">
            </div>
            <div class="form-group">
                <label for="mailSubject">Email subject:</label>
                <input type="text" class="form-control mailSubject" name="mailSubject" placeholder="Mail subject">
            </div>
            <div class="form-group">
                <label for="mailContent">HTML content of mail:</label>
                <textarea type="textarea" class="form-control htmlText mailContent" name="mailContent" rows="15"></textarea>
            </div>
            <div class="form-group">
                <div class="errorsBox text-danger"></div>
                <div class="text-info uploadedFilesList"></div>
                <div class="uploadedFilesInputs"></div>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
                        0%
                    </div>
                </div>
                <div id="fileUploadButton" class="btn btn-info">Add file
                    <input name="files[]" type="file" id="fileupload" class="fileinputButton" multiple="">
                </div>
            </div>
            <div class="form-inline form-group">
                <button id="submitBtn" type="submit" class="btn btn-primary btn-lg">Submit</button>
                <button id="resetBtn" type="reset" class="btn btn-warning btn-lg">Clear</button>
            </div>
        </form>
    </div>
    <div class="col-xs-2"></div>
</div>