<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Mail Test</title>
        
        <meta charset="utf-8">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="Content-language" content="ru-RU"> 
        
        <!-- css styles -->
        <link href="/css/reset.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/css/lib/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/css/lib/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/css/style.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
        
        <!-- js scripts -->
        <script src="/js/lib/jquery.min.js" type="text/javascript"></script>
        <script src="/js/lib/bootstrap.min.js" type="text/javascript"></script>
        <script src="/js/lib/tinymce/tinymce.min.js" type="text/javascript"></script>
        <script src="js/lib/vendor/jquery.ui.widget.js" type="text/javascript"></script>
        <script src="js/lib/jquery.iframe-transport.js" type="text/javascript"></script>
        <script src="js/lib/jquery.fileupload.js" type="text/javascript"></script>
        <script type="text/javascript" src="/js/main.js"></script>
    </head>
    <body>
        <section class="head ">
            <h1 class="h1 title text-center">Online email sender</h1>
            <hr>
        </section>
        <section class="content">
                <?= $this->content; ?>
        </section>
        <div class="loader">
        </div>
    </body>
</html>